# Generated by Django 3.2.13 on 2022-04-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='item_desc',
        ),
    ]
