# Generated by Django 3.2.13 on 2022-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_item_description_item_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com.ar/imgres?imgurl=https%3A%2F%2Fcuculi.com%2Fassets%2Fimages%2Fmeal-default-img.jpg&imgrefurl=https%3A%2F%2Fcuculi.com%2Fvenues%2Fgorin-&tbnid=-fO_excvO9BrdM&vet=10CBYQxiAoAmoXChMIwJbTl4qs9wIVAAAAAB0AAAAAEAc..i&docid=9vLw9xlY8VTvCM&w=320&h=320&itg=1&q=placeholder%20default%20food%20image&ved=0CBYQxiAoAmoXChMIwJbTl4qs9wIVAAAAAB0AAAAAEAc', max_length=500),
        ),
    ]
