# Generated by Django 3.2.13 on 2022-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoOv1u88NArCJTi42Vvb_JPqSbFeAZ9m2PFA&usqp=CAU', max_length=500),
        ),
    ]
