# Generated by Django 3.2.13 on 2022-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.koelnmesse.io/ism/redaktionell/global/img/website-structure/trade-fair/trade-fair/corona/stay-safe/stay-safe_icon_7_t01_1025.jpg', max_length=500),
        ),
    ]
