# Generated by Django 3.2.13 on 2022-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com.ar/url?sa=i&url=https%3A%2F%2Fwww.ism-cologne.com%2Ftrade-fair%2Fism%2Fre-start-koelnmesse%2Fstay-safe%2F&psig=AOvVaw0xMHebX_EouY2av3D0uzqA&ust=1650868391482000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMCW05eKrPcCFQAAAAAdAAAAABAP', max_length=500),
        ),
    ]
