# Generated by Django 3.2.13 on 2022-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://jeffs-burger.ch/wp-content/uploads/2020/12/gst-default-placeholder-4-1024x1024.jpg', max_length=500),
        ),
    ]
